UserTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.userTable}
    SSESpecification:
      SSEEnabled: true
    AttributeDefinitions:
      - AttributeName: address
        AttributeType: S
    KeySchema:
      - AttributeName: address
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 10
      WriteCapacityUnits: 10
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES